# Generated by Django 3.0.3 on 2020-12-03 13:42

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import jsonfallback.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contribution_plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.UUIDField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='ContractId', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='ContractUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('version', models.IntegerField()),
                ('amount_notified', models.FloatField(db_column='AmountNotified')),
                ('amount_rectified', models.FloatField(db_column='AmountRectified')),
                ('amount_due', models.FloatField(db_column='AmountDue')),
                ('payment_due_date', core.fields.DateTimeField(db_column='PaymentDueDate')),
                ('status', models.SmallIntegerField(db_column='Status')),
                ('payment_reference', models.CharField(db_column='PaymentReference', max_length=255)),
                ('json_ext', jsonfallback.fields.FallbackJSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated')),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', null=True)),
                ('contract_from', core.fields.DateTimeField(db_column='ContractFrom')),
                ('contract_to', core.fields.DateTimeField(null=True, verbose_name='ContractTo')),
            ],
            options={
                'db_table': 'tblContract',
            },
        ),
        migrations.CreateModel(
            name='ContractContributionPlanDetails',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.UUIDField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='ContractContributionPlanDetailsId', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='ContractContributionPlanDetailsUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('version', models.IntegerField()),
                ('json_ext', jsonfallback.fields.FallbackJSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated')),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', null=True)),
            ],
            options={
                'db_table': 'tblContractContributionPlanDetails',
            },
        ),
        migrations.CreateModel(
            name='ContractMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='contract.Contract')),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contract', to='core.MutationLog')),
            ],
            options={
                'db_table': 'contract_ContractMutation',
            },
        ),
        migrations.CreateModel(
            name='ContractDetails',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.UUIDField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='ContractDetailsId', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='ContractDetailsUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('json_ext', jsonfallback.fields.FallbackJSONField(blank=True, db_column='Json_ext', null=True)),
                ('json_param', jsonfallback.fields.FallbackJSONField(blank=True, db_column='Json_param', null=True)),
                ('json_param_history', jsonfallback.fields.FallbackJSONField(blank=True, db_column='Json_param_history', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated')),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', null=True)),
                ('contract', models.ForeignKey(db_column='ContractUUID', on_delete=django.db.models.deletion.DO_NOTHING, to='contract.Contract')),
                ('contribution_plan_bundle', models.ForeignKey(db_column='ContributionPlanBundleUUID', on_delete=django.db.models.deletion.DO_NOTHING, to='contribution_plan.ContributionPlanBundle')),
            ],
            options={
                'db_table': 'tblContractDetails',
            },
        ),
    ]
