# Generated by Django 3.0.3 on 2020-12-03 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policy', '0001_initial'),
        ('policyholder', '0001_initial'),
        ('contract', '0001_initial'),
        ('contribution_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdetails',
            name='policy_holder_insuree',
            field=models.ForeignKey(db_column='PolicyHolderInsureeUUID', on_delete=django.db.models.deletion.DO_NOTHING, to='policyholder.PolicyHolderInsuree'),
        ),
        migrations.AddField(
            model_name='contractdetails',
            name='user_created',
            field=models.ForeignKey(db_column='UserCreatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contractdetails_CreatedUUID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractdetails',
            name='user_updated',
            field=models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='contractdetails_UpdatedUUID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractcontributionplandetails',
            name='contract_details',
            field=models.ForeignKey(db_column='ContractDetailsUUID', on_delete=django.db.models.deletion.DO_NOTHING, to='contract.ContractDetails'),
        ),
        migrations.AddField(
            model_name='contractcontributionplandetails',
            name='contribution_plan',
            field=models.ForeignKey(db_column='ContributionPlanUUID', on_delete=django.db.models.deletion.DO_NOTHING, to='contribution_plan.ContributionPlan'),
        ),
        migrations.AddField(
            model_name='contractcontributionplandetails',
            name='policy',
            field=models.ForeignKey(db_column='PolicyUUID', on_delete=django.db.models.deletion.DO_NOTHING, to='policy.Policy'),
        ),
        migrations.AddField(
            model_name='contractcontributionplandetails',
            name='user_created',
            field=models.ForeignKey(db_column='UserCreatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contractcontributionplandetails_CreatedUUID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractcontributionplandetails',
            name='user_updated',
            field=models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='contractcontributionplandetails_UpdatedUUID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='policy_holder',
            field=models.ForeignKey(db_column='PolicyHolderUUID', on_delete=django.db.models.deletion.DO_NOTHING, to='policyholder.PolicyHolder'),
        ),
        migrations.AddField(
            model_name='contract',
            name='user_created',
            field=models.ForeignKey(db_column='UserCreatedUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contract_CreatedUUID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='user_updated',
            field=models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='contract_UpdatedUUID', to=settings.AUTH_USER_MODEL),
        ),
    ]
